using Mixtri.Core.Export;
using Mixtri.Core.Timeline;

namespace Mixtri.Tests;

/// <summary>
/// Regression tests for the per-source zoom keyframe selection used when the exporter
/// builds one compositor per source recording. A zoom created on an appended clip lives
/// in that clip's source-time space, so applying it to the primary recording's compositor
/// would zoom the wrong footage at the wrong time (and vice versa).
/// </summary>
[TestClass]
public sealed class ExportZoomKeyframeSelectionTests
{
    private const string Primary = @"C:\rec\primary\video.mp4";
    private const string Appended = @"C:\rec\appended\video.mp4";

    private static TimelineModel ModelWith(params ZoomKeyframe[] keyframes)
    {
        var model = new TimelineModel { PrimaryVideoFilePath = Primary };
        model.ZoomKeyframes.AddRange(keyframes);
        return model;
    }

    private static ZoomKeyframe Manual(string? sourceFile, double timestampSec = 1) => new()
    {
        Timestamp = TimeSpan.FromSeconds(timestampSec),
        IsManual = true,
        SourceVideoFilePath = sourceFile,
    };

    [TestMethod]
    public void AppendedKeyframe_IsNotAppliedToThePrimaryRecording()
    {
        var appendedZoom = Manual(Appended);
        var model = ModelWith(Manual(null), appendedZoom);

        var primaryKeyframes = SegmentFrameComposer.SelectManualZoomKeyframes(model, Primary);

        Assert.AreEqual(1, primaryKeyframes.Count);
        Assert.IsNull(primaryKeyframes[0].SourceVideoFilePath,
            "Only the primary recording's own keyframes drive its compositor");
    }

    [TestMethod]
    public void AppendedRecording_GetsItsOwnKeyframes()
    {
        var model = ModelWith(Manual(null), Manual(Appended, 4));

        var appendedKeyframes = SegmentFrameComposer.SelectManualZoomKeyframes(model, Appended);

        Assert.AreEqual(1, appendedKeyframes.Count);
        Assert.AreEqual(Appended, appendedKeyframes[0].SourceVideoFilePath);
    }

    [TestMethod]
    public void PrimaryKeyframeStoredWithItsExplicitPath_StillMatchesThePrimary()
    {
        var model = ModelWith(Manual(Primary));

        Assert.AreEqual(1, SegmentFrameComposer.SelectManualZoomKeyframes(model, Primary).Count);
        Assert.AreEqual(0, SegmentFrameComposer.SelectManualZoomKeyframes(model, Appended).Count);
    }

    [TestMethod]
    public void PathComparison_IsCaseInsensitive()
    {
        var model = ModelWith(Manual(Appended.ToUpperInvariant()));

        Assert.AreEqual(1, SegmentFrameComposer.SelectManualZoomKeyframes(model, Appended).Count);
    }

    [TestMethod]
    public void AutoGeneratedKeyframes_AreNotSynced()
    {
        var model = ModelWith(new ZoomKeyframe
        {
            Timestamp = TimeSpan.FromSeconds(1),
            IsManual = false,
            SourceClickTicks = 123,
        });

        Assert.AreEqual(0, SegmentFrameComposer.SelectManualZoomKeyframes(model, Primary).Count,
            "Auto-zooms are rebuilt from click data, not synced as manual keyframes");
    }

    [TestMethod]
    public void UnknownPrimaryPath_TreatsUnattributedKeyframesAsPrimary()
    {
        // Legacy projects have no PrimaryVideoFilePath; unattributed keyframes then
        // belong to whatever source is being rendered.
        var model = new TimelineModel();
        model.ZoomKeyframes.Add(Manual(null));

        Assert.IsTrue(SegmentFrameComposer.BelongsToSource(model.ZoomKeyframes[0], Primary, null));
    }
}
