using Mixtri.Core.Models;
using Mixtri.Core.Processing;

namespace Mixtri.Tests.TestSupport;

/// <summary>
/// Shared builders for <see cref="MouseRecordingData"/> fixtures that were re-implemented
/// four times (<c>AutoZoomEngineTests.BuildRecordingWithClicks</c>,
/// <c>CursorSmootherTests.BuildRecording</c>/<c>BuildStopAndGo</c>/<c>BuildMoveStallMove</c>,
/// <c>AppendedZoomRegenerationTests.MakeMouse</c>, <c>ZoomSegmentProgressTests.BuildRecordingWithClicks</c>).
/// Each method mirrors one existing shape exactly; <c>tickFrequency</c> defaults to the
/// 10,000,000 (100ns ticks, matching <see cref="Stopwatch"/>) value every call site already
/// used, but stays a parameter for <see cref="WithClickTicks"/>, which is called with other
/// values (e.g. 1000) in <c>AppendedZoomRegenerationTests</c>.
/// </summary>
internal static class TestMouseRecordingBuilder
{
    /// <summary>
    /// Mirrors AutoZoomEngineTests.BuildRecordingWithClicks / ZoomSegmentProgressTests.BuildRecordingWithClicks
    /// (identical implementations): a steady 100Hz move-sample stream at (960, 540) plus the given clicks.
    /// </summary>
    public static MouseRecordingData WithClicks(
        double durationSeconds,
        List<(double timeSeconds, int x, int y)> clicks,
        double tickFrequency = 10_000_000.0)
    {
        long startTick = 0;
        long endTick = (long)(durationSeconds * tickFrequency);
        int sampleCount = Math.Max(2, (int)(durationSeconds * 100));

        var samples = new List<MouseSample>();
        for (int i = 0; i < sampleCount; i++)
        {
            double t = i * durationSeconds / (sampleCount - 1);
            samples.Add(new MouseSample
            {
                TimestampTicks = (long)(t * tickFrequency),
                X = 960,
                Y = 540,
                EventKind = MouseEventKind.Move,
                Button = MouseButton.None,
                ScrollDelta = 0,
            });
        }

        var clickEvents = clicks.Select(c => new ClickEvent(
            TimestampTicks: (long)(c.timeSeconds * tickFrequency),
            X: c.x,
            Y: c.y,
            Button: MouseButton.Left,
            IsDown: true
        )).ToList();

        return new MouseRecordingData
        {
            Samples = samples,
            Clicks = clickEvents,
            StartTimestampTicks = startTick,
            EndTimestampTicks = endTick,
            TickFrequency = tickFrequency,
        };
    }

    /// <summary>
    /// Mirrors CursorSmootherTests.BuildRecording: samples generated by a callback receiving the
    /// sample index and returning (x, y).
    /// </summary>
    public static MouseRecordingData WithPositions(
        int sampleCount,
        double sampleRateHz,
        Func<int, (double x, double y)> positionFunc,
        double tickFrequency = 10_000_000.0)
    {
        long startTick = 0;
        double ticksPerSample = tickFrequency / sampleRateHz;
        var samples = new List<MouseSample>(sampleCount);

        for (int i = 0; i < sampleCount; i++)
        {
            var (x, y) = positionFunc(i);
            samples.Add(new MouseSample
            {
                TimestampTicks = startTick + (long)(i * ticksPerSample),
                X = (int)Math.Round(x),
                Y = (int)Math.Round(y),
                EventKind = MouseEventKind.Move,
                Button = MouseButton.None,
                ScrollDelta = 0,
            });
        }

        return new MouseRecordingData
        {
            Samples = samples,
            StartTimestampTicks = startTick,
            EndTimestampTicks = samples[^1].TimestampTicks,
            TickFrequency = tickFrequency,
        };
    }

    /// <summary>
    /// Mirrors CursorSmootherTests.BuildStopAndGo: explicit move samples plus optional click
    /// samples/events, at the given sample rate.
    /// </summary>
    public static MouseRecordingData WithMoveAndClickSamples(
        double sampleRateHz,
        IReadOnlyList<(double t, double x, double y)> movePoints,
        IReadOnlyList<(double t, double x, double y)>? clickDowns = null,
        double tickFrequency = 10_000_000.0)
    {
        var samples = new List<MouseSample>();
        foreach (var (t, x, y) in movePoints)
        {
            samples.Add(new MouseSample
            {
                TimestampTicks = (long)(t * tickFrequency),
                X = (int)Math.Round(x),
                Y = (int)Math.Round(y),
                EventKind = MouseEventKind.Move,
                Button = MouseButton.None,
            });
        }

        var clicks = new List<ClickEvent>();
        if (clickDowns is not null)
        {
            foreach (var (t, x, y) in clickDowns)
            {
                long tick = (long)(t * tickFrequency);
                samples.Add(new MouseSample
                {
                    TimestampTicks = tick,
                    X = (int)Math.Round(x),
                    Y = (int)Math.Round(y),
                    EventKind = MouseEventKind.ButtonDown,
                    Button = MouseButton.Left,
                });
                clicks.Add(new ClickEvent(tick, (int)Math.Round(x), (int)Math.Round(y), MouseButton.Left, true));
            }
            samples.Sort((p, q) => p.TimestampTicks.CompareTo(q.TimestampTicks));
        }

        return new MouseRecordingData
        {
            Samples = samples,
            Clicks = clicks,
            StartTimestampTicks = 0,
            EndTimestampTicks = samples[^1].TimestampTicks,
            TickFrequency = tickFrequency,
        };
    }

    /// <summary>
    /// Mirrors AppendedZoomRegenerationTests.MakeMouse: a click-only recording keyed by explicit
    /// tick timestamps (used with a tickFrequency of 1000 at that call site, not the 10,000,000
    /// default used everywhere else).
    /// </summary>
    public static MouseRecordingData WithClickTicks(
        long startTicks, double tickFrequency, params (long Ticks, int X, int Y)[] clicks)
    {
        return new MouseRecordingData
        {
            StartTimestampTicks = startTicks,
            EndTimestampTicks = startTicks + 100_000,
            TickFrequency = tickFrequency,
            Clicks = clicks.Select(c => new ClickEvent(c.Ticks, c.X, c.Y, MouseButton.Left, true)).ToList(),
        };
    }
}
