namespace Musio.Tests;

using Musio.Core.Processing;
using Musio.Core.Models;

[TestClass]
public sealed class CursorSmootherTests
{
    private const double TickFrequency = 10_000_000.0; // 1 tick = 100 ns (like Stopwatch on most systems)
    private const int TargetFps = 60;

    /// <summary>
    /// Builds a MouseRecordingData with samples generated by a callback.
    /// The callback receives the sample index and returns (x, y).
    /// </summary>
    private static MouseRecordingData BuildRecording(int sampleCount, double sampleRateHz,
        Func<int, (double x, double y)> positionFunc)
    {
        long startTick = 0;
        double ticksPerSample = TickFrequency / sampleRateHz;
        var samples = new List<MouseSample>(sampleCount);

        for (int i = 0; i < sampleCount; i++)
        {
            var (x, y) = positionFunc(i);
            samples.Add(new MouseSample
            {
                TimestampTicks = startTick + (long)(i * ticksPerSample),
                X = (int)Math.Round(x),
                Y = (int)Math.Round(y),
                EventKind = MouseEventKind.Move,
                Button = MouseButton.None,
                ScrollDelta = 0,
            });
        }

        return new MouseRecordingData
        {
            Samples = samples,
            StartTimestampTicks = startTick,
            EndTimestampTicks = samples[^1].TimestampTicks,
            TickFrequency = TickFrequency,
        };
    }

    #region None / Passthrough

    [TestMethod]
    public void SmoothPath_WithNone_ReturnsUnmodifiedPositions()
    {
        // Arrange: straight diagonal line at 200 Hz for 1 second
        var recording = BuildRecording(200, 200, i => (i, i));

        var smoother = new CursorSmoother
        {
            Algorithm = SmoothingAlgorithm.SpringPhysics,
            Strength = SmoothingStrength.None,
        };

        // Act
        var result = smoother.SmoothPath(recording, TargetFps);

        // Assert: each output frame should match the raw interpolated position
        foreach (var pos in result)
        {
            double expected = pos.TimestampSeconds * 200; // linear path: x = y = t * sampleRate
            Assert.AreEqual(expected, pos.X, 1.5, $"X mismatch at t={pos.TimestampSeconds:F4}");
            Assert.AreEqual(expected, pos.Y, 1.5, $"Y mismatch at t={pos.TimestampSeconds:F4}");
        }
    }

    #endregion

    #region Spring Physics

    [TestMethod]
    public void SmoothPath_SpringPhysics_SmoothsJitter()
    {
        // Arrange: sine wave with random jitter
        var rng = new Random(42);
        var recording = BuildRecording(600, 200, i =>
        {
            double t = i / 200.0;
            double baseX = 500 + 200 * Math.Sin(2 * Math.PI * 0.5 * t);
            double baseY = 400 + 150 * Math.Cos(2 * Math.PI * 0.5 * t);
            return (baseX + rng.NextDouble() * 20 - 10, baseY + rng.NextDouble() * 20 - 10);
        });

        var smoother = new CursorSmoother
        {
            Algorithm = SmoothingAlgorithm.SpringPhysics,
            Strength = SmoothingStrength.Smooth,
        };

        // Act
        var smoothed = smoother.SmoothPath(recording, TargetFps);

        // Assert: smoothed derivative std-dev should be lower than raw
        double rawJitter = ComputeDerivativeStdDev(GetRawFrames(recording, TargetFps));
        double smoothJitter = ComputeDerivativeStdDev(smoothed);

        Assert.IsTrue(smoothJitter < rawJitter,
            $"Smoothed jitter ({smoothJitter:F2}) should be less than raw ({rawJitter:F2})");
    }

    #endregion

    #region One Euro Filter

    [TestMethod]
    public void SmoothPath_OneEuro_ReducesHighFrequencyNoise()
    {
        var rng = new Random(123);
        var recording = BuildRecording(600, 200, i =>
        {
            double t = i / 200.0;
            double baseX = 300 + 100 * t;
            double baseY = 300 + 50 * Math.Sin(2 * Math.PI * 1.0 * t);
            return (baseX + rng.NextDouble() * 16 - 8, baseY + rng.NextDouble() * 16 - 8);
        });

        var smoother = new CursorSmoother
        {
            Algorithm = SmoothingAlgorithm.OneEuroFilter,
            Strength = SmoothingStrength.Medium,
        };

        var smoothed = smoother.SmoothPath(recording, TargetFps);

        double rawJitter = ComputeDerivativeStdDev(GetRawFrames(recording, TargetFps));
        double smoothJitter = ComputeDerivativeStdDev(smoothed);

        Assert.IsTrue(smoothJitter < rawJitter,
            $"One-Euro smoothed jitter ({smoothJitter:F2}) should be less than raw ({rawJitter:F2})");
    }

    #endregion

    #region Catmull-Rom

    [TestMethod]
    public void SmoothPath_CatmullRom_InterpolatesSmoothly()
    {
        // Arrange: L-shaped path (right then down)
        var recording = BuildRecording(400, 200, i =>
        {
            double t = i / 200.0;
            double x, y;
            if (t < 1.0)
            {
                x = 100 + 400 * t;
                y = 100;
            }
            else
            {
                x = 500;
                y = 100 + 400 * (t - 1.0);
            }
            return (x, y);
        });

        var smoother = new CursorSmoother
        {
            Algorithm = SmoothingAlgorithm.CatmullRomSpline,
            Strength = SmoothingStrength.Subtle,
        };

        var smoothed = smoother.SmoothPath(recording, TargetFps);

        // Verify output follows general path: x generally increases then plateaus,
        // y starts low then increases
        Assert.IsTrue(smoothed.Count > 0);

        var first = smoothed[0];
        var last = smoothed[^1];
        Assert.IsTrue(last.X > first.X, "X should increase overall");
        Assert.IsTrue(last.Y > first.Y, "Y should increase overall");
    }

    #endregion

    #region Start and End Position

    [TestMethod]
    public void SmoothPath_PreservesStartAndEndPositions()
    {
        var recording = BuildRecording(300, 200, i =>
        {
            double t = i / 200.0;
            return (100 + 300 * t, 200 + 100 * t);
        });

        foreach (var algo in new[] { SmoothingAlgorithm.SpringPhysics, SmoothingAlgorithm.OneEuroFilter })
        {
            var smoother = new CursorSmoother
            {
                Algorithm = algo,
                Strength = SmoothingStrength.Subtle,
            };

            var smoothed = smoother.SmoothPath(recording, TargetFps);
            Assert.IsTrue(smoothed.Count > 1);

            var first = smoothed[0];
            Assert.AreEqual(100, first.X, 5.0, $"{algo}: Start X should be near 100");
            Assert.AreEqual(200, first.Y, 5.0, $"{algo}: Start Y should be near 200");

            // End position: allow more tolerance for spring lag
            var last = smoothed[^1];
            Assert.AreEqual(100 + 300 * (recording.Samples.Count - 1) / 200.0, last.X, 50.0,
                $"{algo}: End X should be near final raw X");
        }
    }

    #endregion

    #region Output Length

    [TestMethod]
    public void SmoothPath_OutputLengthMatchesFps()
    {
        double durationSeconds = 2.0;
        int sampleCount = 400;
        var recording = BuildRecording(sampleCount, sampleCount / durationSeconds, i => (i, i));

        var smoother = new CursorSmoother
        {
            Algorithm = SmoothingAlgorithm.SpringPhysics,
            Strength = SmoothingStrength.Medium,
        };

        var smoothed = smoother.SmoothPath(recording, TargetFps);

        int expectedCount = (int)Math.Round(durationSeconds * TargetFps);
        Assert.AreEqual(expectedCount, smoothed.Count,
            $"Expected ~{expectedCount} frames for {durationSeconds}s at {TargetFps} fps, got {smoothed.Count}");
    }

    #endregion

    #region Helpers

    /// <summary>
    /// Gets raw (unsmoothed) frames at the target FPS for comparison.
    /// </summary>
    private static List<SmoothedPosition> GetRawFrames(MouseRecordingData recording, int fps)
    {
        var smoother = new CursorSmoother
        {
            Algorithm = SmoothingAlgorithm.None,
            Strength = SmoothingStrength.None,
        };
        return smoother.SmoothPath(recording, fps);
    }

    /// <summary>
    /// Computes standard deviation of frame-to-frame velocity magnitude changes (jerk proxy).
    /// Lower values indicate a smoother path.
    /// </summary>
    private static double ComputeDerivativeStdDev(List<SmoothedPosition> positions)
    {
        if (positions.Count < 3) return 0;

        var diffs = new List<double>(positions.Count - 1);
        for (int i = 1; i < positions.Count; i++)
        {
            double dx = positions[i].X - positions[i - 1].X;
            double dy = positions[i].Y - positions[i - 1].Y;
            diffs.Add(Math.Sqrt(dx * dx + dy * dy));
        }

        double mean = diffs.Average();
        double variance = diffs.Sum(d => (d - mean) * (d - mean)) / diffs.Count;
        return Math.Sqrt(variance);
    }

    #endregion
}
